version: '3.8'

services:
  backend:
    build: ./backend/clinix_backend
    env_file:
      - .env.prod
    volumes:
      - static_volume:/app/static
    networks:
      - clinix-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/clinix_frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - clinix-network
    restart: unless-stopped

volumes:
  static_volume:

networks:
  clinix-network:
    driver: bridge