# Generated by Django 5.2 on 2025-04-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(default='sickness'),
            preserve_default=False,
        ),
    ]
