# Generated by Django 5.2 on 2025-04-25 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_rename_name_program_title_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='health.client'),
        ),
    ]
